# Generated by Django 2.2.5 on 2023-02-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=True, verbose_name='show this?')),
                ('position', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Category',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article'},
        ),
    ]
